# Generated by Django 4.2.7 on 2023-11-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0002_alter_task_author_alter_task_executor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="label",
            field=models.ManyToManyField(
                blank=True, related_name="label", to="labels.label"
            ),
        ),
    ]
