# Generated by Django 4.2.7 on 2023-11-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0008_alter_task_executor_alter_task_label_alter_task_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="label",
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="labels",
                through="tasks.TaskLabel",
                to="labels.label",
                verbose_name="Labels",
            ),
        ),
    ]
