name: linter-and-test

on: 
  push:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install poetry
      - run: poetry install
      - run: make linter
      - run: make test

      - name: Create reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Test and Report coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage lcov -o coverage/lcov.info
      - name: Sending Reporter
        env:
          GITHUB_TOKEN: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          ./cc-test-reporter after-build -r "$GITHUB_TOKEN" -t lcov