# Generated by Django 4.2.7 on 2023-11-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Status name"
            ),
        ),
    ]
